name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml -e
      - name: Lint XtendM3 Extensions
        run: mvn -B xtendm3:lint --file pom.xml
      - name: Export XtendM3 Extensions
        run: mvn -B xtendm3:export --file pom.xml
      - uses: actions/upload-artifact@v3
        name: Upload exported extensions
        if: ${{ success() }}
        with:
          name: ${{ github.event.repository.name }}
          path: target/exported.zip
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/exported.zip
          asset_name: unsigned-extensions
          tag: unsigned
          overwrite: true
          body: "XtendM3 unsigned extensions"
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
